'''

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten 
pentagonal numbers are: 

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ... 

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 
− 22 = 48, is not pentagonal. 

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and 
difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of 
D? 

'''

def getPentagonals(count=10000):
	n = 1
	while n < count:
		yield n * (3 * n - 1) // 2
		n += 1

pentagonall = list(getPentagonals())
pentagonals = set(pentagonall)

def foursHasProperty(pair1, pair2):
	return (pair1 + pair2) in pentagonals and (abs(pair1 - pair2) in pentagonals)
		
if __name__ == '__main__':
	n = len(pentagonals) - 1
# 	print([i for i in range(len(pentagonals) - 1) if foursHasProperty(pentagonals[i], pentagonals[i + 1])])
	print([(pentagonall[i + dist] - pentagonall[i]) for dist in range(1, n) for i in range(n - dist) if foursHasProperty(pentagonall[i], pentagonall[i + dist])])
