'''

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten 
pentagonal numbers are: 

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ... 

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 
− 22 = 48, is not pentagonal. 

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and 
difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of 
D? 

'''

def getPentagonals(count=100):
	n = 1
	while n < count:
		yield n * (3 * n - 1) // 2
		n += 1

pentagonall = list(getPentagonals())
pentagonals = set(pentagonall)

def hasProperty(p1, p2):
	return (p1 + p2) in pentagonals and (abs(p1 - p2) in pentagonals)
		
if __name__ == '__main__':
	print([i for i in range(len(pentagonals) - 1) if hasProperty(pentagonals[i], pentagonals[i + 1])])
